### PR TITLE
[AJ-537] support optional syncPermissions param

### PR DESCRIPTION
**Pull request by jordansafer**
This PR adds support for optionally syncing permissions in TDR snapshot import-by-copy. The importJob request will now contain an optional boolean field specifying whether the TDR permissions sync is enabled.

Tested end to end with TDR, Terra-UI, Orch, import service, rawls. I tested passing true, false, and no param paths.

Have you read [CONTRIBUTING.md](../CONTRIBUTING.md) lately? If not, do that first.

I, the developer opening this PR, do solemnly pinky swear that:

- [x] I've followed [the instructions](https://github.com/broadinstitute/firecloud-orchestration/blob/develop/CONTRIBUTING.md#api-changes) if I've made any changes to the API, _especially_ if they're breaking changes
- [x] I've updated the RC_XXX release ticket with any manual steps required to release this change
- [x] I've updated the [FISMA documentation](https://github.com/broadinstitute/firecloud-orchestration/blob/develop/CONTRIBUTING.md#fisma-documentation-changes) if I've made any security-related changes, including auth, encryption, or auditing

In all cases:

- [ ] Get two thumbsworth of review and PO signoff if necessary
- [ ] Verify all tests go green
- [ ] Squash and merge; you can delete your branch after this **unless it's for a hotfix**. In that case, don't delete it!
- [ ] Test this change deployed correctly and works on dev environment after deployment

### CODE REVIEW

**Comment by davidangb** [comment]
I'm imagining that we may add more flags to the import process parallel to `tdrSyncPermissions`. AJ-136 is an outstanding (and low priority) feature request that would add a flag; we may need other ones for handling sensitive data imports. What do you think about nesting `tdrSyncPermissions` under an `options` key-value map where we could add other flags later? Since `tdrSyncPermissions` is irrelevant for TSV and PFB imports, this would also make it less glaring for those imports.

**Review by davidangb — COMMENTED** [review]
syntax looks good to me. I'm still wondering about nesting the `tdrSyncPermissions` flag under an `options` map - what do you think about that?

**Comment by jordansafer** [comment]
> I'm imagining that we may add more flags to the import process parallel to `tdrSyncPermissions`. [AJ-136](https://broadworkbench.atlassian.net/browse/AJ-136) is an outstanding (and low priority) feature request that would add a flag; we may need other ones for handling sensitive data imports. What do you think about nesting `tdrSyncPermissions` under an `options` key-value map where we could add other flags later? Since `tdrSyncPermissions` is irrelevant for TSV and PFB imports, this would also make it less glaring for those imports.

I like the idea of using an options map! I'll add it. I did think the tdrSyncPermissions looked messy.

**Review by davidangb — APPROVED** [review]
:+1: assuming tests pass

**Review by sagehen03 — APPROVED** [review]

**Pull request merged**
