### PR TITLE
Facet render hints for aggregate types.

### PR DESCRIPTION
**Pull request by rushtong**
This is required for https://broadinstitute.atlassian.net/browse/GAWB-976

The facet rendering on the library page requires more information than is currently available for the aggregate types. For example, both phenotype and project are string types, but require different forms of rendering in the UI. This change allows the UI to make the right display decision. 

Even though `library:numSubjects` is not currently an aggregate field, the UI does call for it at some point so this PR tries to anticipate that requirement.

---

- [x] **Submitter**: Include the JIRA issue number in the PR description
- [x] **Submitter**: Make sure Swagger is updated if API changes
- [x] **Submitter**: If updating admin endpoints, also update [firecloud-admin-cli](https://github.com/broadinstitute/firecloud-admin-cli)
- [x] **Submitter**: Check documentation and code comments. Add explanatory PR comments if helpful.
- [x] **Submitter**: JIRA ticket checks:
  * Acceptance criteria exists and is met
  * Note any changes to implementation from the description
  * Add notes on what you've tested
- [x] **Submitter**: Update RC_XXX release ticket with any config or environment changes necessary
- [x] **Submitter**: Update FISMA documentation if changes to:
  * Authentication
  * Authorization
  * Encryption
  * Audit trails
- [x] **Submitter**: If you're adding new libraries, sign us up to security updates for them
- [x] Tell the tech lead (TL) that the PR exists if they wants to look at it
- [x] Anoint a lead reviewer (LR). **Assign PR to LR**
* Review cycle:
  * LR reviews
  * Rest of team may comment on PR at will
  * **LR assigns to submitter** for feedback fixes
  * Submitter rebases to develop again if necessary
  * Submitter makes further commits. DO NOT SQUASH
  * Submitter updates documentation as needed
  * Submitter **reassigns to LR** for further feedback
- [x] **TL** sign off
- [x] **LR** sign off
- [x] **Product Owner** sign off
- [x] **Assign to submitter** to finalize
- [x] **Submitter**: Verify all tests go green, including CI tests
- [x] **Submitter**: Squash commits and merge to develop
- [x] **Submitter**: Delete branch after merge
- [x] **Submitter**: **Test this change works on dev environment after deployment**. YOU own getting it fixed if dev isn't working for ANY reason!
- [x] **Submitter**: Verify swagger UI on dev environment still works after deployment
- [x] **Submitter**: Inform other teams of any API changes via hipchat and/or email
- [x] **Submitter**: Mark JIRA issue as resolved once this checklist is completed

### CODE REVIEW

**Comment by skwalker** [comment]
👍 looks fine to me

**Comment by davidangb** [comment]
Some thoughts:
1. I'm fine with this as-is.
2. We've been using `renderHint` to control display on the cataloging (edit) screen. This PR overrides `renderHint` to control display of facets. Was this intentional? I assume so ... just wanted to make sure.
3. I suspect in the future we may have more configs for facets. In that case, it would probably make sense to go for a structure like:
```
    "library:projectName": {
      "title": "Project Name",
      "type": "string",
      "aggregate": {
        "renderHint": "checkbox",
        "autocomplete": false,
        "order": { "_count" : "asc" }
      }
    },
```
but we don't have to do that yet.

**Comment by rushtong** [comment]
2. Technically, this doesn't override them in the wizard because the wizard
isn't using these properties - it's using a separate set of properties
defined locally for just the wizard. The only reason I was using
`renderHint` was to be consistent.

3. I like your suggestion. Let me look into how much of a change it is in
orchestration.

**Comment by davidangb** [comment]
agreed on bullet point 2 - and by "override" I really meant, "you're using the same name as", not that you're overwriting the other renderHints. All set!

**Comment by davidangb** [comment]
👍

**Review by davidangb — APPROVED** [review]

**Pull request merged**
