### PR TITLE
Our endpoint, sans tests

### PR DESCRIPTION
**Pull request by MattPutnam**
This is the endpoint for updating a method configuration inside a workspace.

### CODE REVIEW

**Comment by MatthewBemis** [comment]
Would it make more sense to have this as part of MethodConfigurationService? Other than that, the actual content gets a (thumbsup) from me

**Comment by MattPutnam** [comment]
There aren't any tests yet.  I talked with Greg and he's okay with leaving them off for now.

**Comment by eddiebroad** [comment]
@MattPutnam  if there are no tests and Greg is okay with absence of tests.  then I am okay with absence of tests.  At this point, not sure if you wanna rebase and then we could complete this?

**Comment by eddiebroad** [comment]
and in addition to that maybe address any possible issue with Jenkins!

**Comment by eddiebroad** [comment]
yay for being rebased.  I wonder if any merge should be delayed until the recent build issue is investigated?

**Pull request merged**
