### PR TITLE
AS-543: Remove Logit metrics code

### PR DESCRIPTION
**Pull request by MatthewBemis**
\<your comments for this PR go here\>

Have you read [CONTRIBUTING.md](../CONTRIBUTING.md) lately? If not, do that first.

I, the developer opening this PR, do solemnly pinky swear that:

- [ ] I've followed [the instructions](https://github.com/broadinstitute/firecloud-orchestration/blob/develop/CONTRIBUTING.md#api-changes) if I've made any changes to the API, _especially_ if they're breaking changes
- [ ] I've updated the RC_XXX release ticket with any manual steps required to release this change
- [ ] I've updated the [FISMA documentation](https://github.com/broadinstitute/firecloud-orchestration/blob/develop/CONTRIBUTING.md#fisma-documentation-changes) if I've made any security-related changes, including auth, encryption, or auditing

In all cases:

- [ ] Get two thumbsworth of review and PO signoff if necessary
- [ ] Verify all tests go green
- [ ] Squash and merge; you can delete your branch after this **unless it's for a hotfix**. In that case, don't delete it!
- [ ] Test this change deployed correctly and works on dev environment after deployment

### CODE REVIEW

**Comment by davidangb** [comment]
love this PR ... aaaand, I don't know who owns these metrics now, we should make sure they're absolutely not being used by anyone anywhere

**Comment by MatthewBemis** [comment]
@davidangb I'll see if I can figure that out. Another benefit of removing this is that I believe it's the only thing that's still calling the old rawls admin statistics endpoint. I would need to double check with Chet to make sure it's definitely no longer needed for NCI reporting but I suspect that it's not based on looking through Logit. It would be really nice to get rid of it- it's a bunch of pretty ugly code and I'd like if nobody had to think about maintaining it.

I have a rawls branch to remove that [here](https://github.com/broadinstitute/rawls/compare/mb-remove-stats-endpoint), but it can sit on the back burner for a bit.

**Comment by davidangb** [comment]
@MatthewBemis did you ever follow up on this? It would be great to merge this.

**Comment by MatthewBemis** [comment]
@davidangb Thanks for the reminder, I just sent out a Slack message and will follow up via email as well depending on the response the Slack msg gets

**Comment by MatthewBemis** [comment]
This is now clear for merge (after review of course)

**Review by davidangb — APPROVED** [review]
:+1: thanks!

As a follow-on, could you clean up the .conf file, too? https://github.com/broadinstitute/firecloud-develop/blob/dev/base-configs/firecloud-orchestration/firecloud-orchestration.conf.ctmpl#L343

**Comment by MatthewBemis** [comment]
@davidangb good call, just opened https://github.com/broadinstitute/firecloud-develop/pull/2395

**Review by ansingh7115 — APPROVED** [review]

**Pull request merged**
