### PR TITLE
Update netty-handler from 4.1.84.Final to 4.1.85.Final [AJ-737]

### PR DESCRIPTION
**Pull request by broadbot**
Updates [io.netty:netty-handler](https://github.com/netty/netty) from 4.1.84.Final to 4.1.85.Final.

I'll automatically update this PR to resolve conflicts as long as you don't change it yourself.

If you'd like to skip this version, you can just close this PR. If you have any feedback, just mention me in the comments below.

Configure Scala Steward for your repository with a [`.scala-steward.conf`](https://github.com/scala-steward-org/scala-steward/blob/d87ab874d722295a1cb5570ee3dda2a201bf5d70/docs/repo-specific-configuration.md) file.

Have a fantastic day writing Scala!

<details>
<summary>Adjust future updates</summary>

Add this to your `.scala-steward.conf` file to ignore future updates of this dependency:
```
updates.ignore = [ { groupId = "io.netty", artifactId = "netty-handler" } ]
```
Or, add this to slow down future updates of this dependency:
```
dependencyOverrides = [{
  pullRequests = { frequency = "@monthly" },
  dependency = { groupId = "io.netty", artifactId = "netty-handler" }
}]
```
</details>

labels: library-update, commit-count:1

### CODE REVIEW

**Comment by davidangb** [comment]
fiab-start failed, but long enough ago that Jenkins doesn't have the history. Jenkins retest.

**Comment by davidangb** [comment]
Why didn't that work?

Jenkins retest

**Comment by choover-broad** [comment]
jenkins retest

**Comment by davidangb** [comment]
jenkins retest

**Review by davidangb — APPROVED** [review]

**Pull request merged**
