### PR TITLE
Fix whitelist_sync regression

### PR DESCRIPTION
**Pull request by MatthewBemis**
Orch could no longer make the call to thurloe to grab the list of currently linked users because this header was dropped. No ticket because it was quicker to fix it.
- [x] **Submitter**: Include the JIRA issue number in the PR description
- [x] **Submitter**: Make sure Swagger is updated if API changes
- [x] **Submitter**: If updating admin endpoints, also update [firecloud-admin-cli](https://github.com/broadinstitute/firecloud-admin-cli)
- [x] **Submitter**: Check documentation and code comments. Add explanatory PR comments if helpful.
- [x] **Submitter**: JIRA ticket checks:
  - Acceptance criteria exists and is met
  - Note any changes to implementation from the description
  - Add notes on what you've tested
- [x] **Submitter**: Update RC_XXX release ticket with any config or environment changes necessary
- [x] **Submitter**: Update FISMA documentation if changes to:
  - Authentication
  - Authorization
  - Encryption
  - Audit trails
- [x] **Submitter**: If you're adding new libraries, sign us up to security updates for them
- [x] Tell the tech lead (TL) that the PR exists if they wants to look at it
- [x] Anoint a lead reviewer (LR). **Assign PR to LR**
- Review cycle:
  - LR reviews
  - Rest of team may comment on PR at will
  - **LR assigns to submitter** for feedback fixes
  - Submitter rebases to develop again if necessary
  - Submitter makes further commits. DO NOT SQUASH
  - Submitter updates documentation as needed
  - Submitter **reassigns to LR** for further feedback
- [x] **TL** sign off
- [x] **LR** sign off
- [x] **Assign to submitter** to finalize
- [ ] **Submitter**: Verify all tests go green, including CI tests
- [ ] **Submitter**: Squash commits and merge to develop
- [ ] **Submitter**: Delete branch after merge
- [ ] **Submitter**: **Test this change works on dev environment after deployment**. YOU own getting it fixed if dev isn't working for ANY reason!
- [ ] **Submitter**: Verify swagger UI on dev environment still works after deployment
- [ ] **Submitter**: Inform other teams of any API changes via hipchat and/or email
- [ ] **Submitter**: Mark JIRA issue as resolved once this checklist is completed

### CODE REVIEW

**Comment by davidangb** [comment]
I'm all for fixing regressions, but ... if the pipeline in question is querying Thurloe, why does it need admin credentials?

**Comment by MatthewBemis** [comment]
@davidangb It doesn't necessarily need _admin_ credentials, it just needs _some_ credentials, otherwise it gets 401'd. I was just putting back what we had before it was dropped here: https://github.com/broadinstitute/firecloud-orchestration/pull/249/files#diff-dfeeee9107bdde9bfc8b72cef89e6bebR370

I have no idea why I said rawls<->orch communication was the issue in the description. I looked at that as being the source of the issue too so I think I just got mixed up 😧

**Comment by rushtong** [comment]
@MatthewBemis - that pipeline does have user credentials. It seems like that's not enough?

**Comment by rushtong** [comment]
@MatthewBemis - I misread that, sorry. I think if it only needs _some_ credentials, we should add the user's.

**Comment by davidangb** [comment]
There may be two use cases here: 1) the current user is linking with NIH and runs through this code path; 2) the whitelist cron is running. In the latter case, there is no user, right? Ideally we'd use the user's creds if we have them, and admin otherwise.

**Comment by MatthewBemis** [comment]
@davidangb yes that sounds right to me. 

Do we want to take this PR as is since it gets us back to the original working state, and file a ticket to take the cleaner approach in the future? Or do we want to implement the ideal approach now?

**Comment by davidangb** [comment]
I say accept as-is, file a future ticket. (edit: "say" not "saw")

**Comment by davidangb** [comment]
( if it wasn't clear, previous comment was a 👍 )

**Comment by MatthewBemis** [comment]
Ticket filed as GAWB-1071

**Pull request merged**
