### PR TITLE
New PR checkboxes

### PR DESCRIPTION
**Pull request by helgridly**
The old checkboxes were too long and nobody was following them. I've factored out most of the information to `CONTRIBUTING.md` and hopefully made it more approachable.

I recommend hitting "view rich diff" for a more pleasant reviewing experience.

### CODE REVIEW

**Comment by MatthewBemis** [comment]
:+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1:

**Comment by dvoet** [comment]
I liked the checkbox "Test this change works on dev environment after deployment" and also verify swagger

**Comment by aednichols** [comment]
I liked the release notes reminder, helped me on a PR earlier today

**Comment by helgridly** [comment]
@aednichols That's in CONTRIBUTING.md now.

**Comment by davidangb** [comment]
+1 to re-adding "Test this change works on dev environment after deployment" or even "Test this change deployed correctly and works on dev environment after deployment", otherwise looks good! :+1:

**Pull request merged**
