### PR TITLE
recreate index if not exists on startup

### PR DESCRIPTION
**Pull request by rushtong**
No jira. FiaBs are failing due to a chicken-egg problem with orc requiring a trial index that isn't on elastic search during the spin up process. 

To test locally, change the `trialIndex` value in `firecloud-orchestration.conf` to be something that isn't already in ES. Orch should still start and create the missing index.
```
elasticsearch { 
  ...
  trialIndex = "trial-testing-777"
  ...
}
```

Have you read [CONTRIBUTING.md](../CONTRIBUTING.md) lately? If not, do that first.

I, the developer opening this PR, do solemnly pinky swear that:

- [x] I've followed [the instructions](https://github.com/broadinstitute/firecloud-orchestration/blob/develop/CONTRIBUTING.md#api-changes) if I've made any changes to the API, _especially_ if they're breaking changes
- [x] I've updated the RC_XXX release ticket with any manual steps required to release this change
- [x] I've updated the [FISMA documentation](https://github.com/broadinstitute/firecloud-orchestration/blob/develop/CONTRIBUTING.md#fisma-documentation-changes) if I've made any security-related changes, including auth, encryption, or auditing

In all cases:

- [x] Get two thumbsworth of review and PO signoff if necessary
- [x] Verify all tests go green
- [x] Squash and merge; you can delete your branch after this **unless it's for a hotfix**. In that case, don't delete it!
- [x] Test this change deployed correctly and works on dev environment after deployment

### CODE REVIEW

**Review by UrsaStutsman — COMMENTED** [review]
Works for me! :)

**Review by breilly2 — APPROVED** [review]
👍  Worked for me! I don't know that it's the correct thing to do for this index but at least it unblocks me. Thanks!

**Review by aednichols — APPROVED** [review]
Intuitively, if `init` makes `indexExists` pass, I think it's doing the right thing.

**Review by kyuksel — APPROVED** [review]
Logically 👍ing based on my conversation with @rushtong.

**Pull request merged**
