### PR TITLE
GAWB-1119: use plain-array deserialization for library metadata update

### PR DESCRIPTION
**Pull request by davidangb**
part of GAWB-1119, but doesn't necessarily fix it all the way.

The library metadata-update API accepts plain json - not the new attribute list format. It does this because:
- we can then take advantage of json schema validation, since metadata is defined in json schema
- we don't need to support entity references

The default deserializer in ModelJsonProtocol uses the new attribute list format. To fix this, I needed to bring a new implicit into scope that uses the plain json format instead.
- [x] **Submitter**: Include the JIRA issue number in the PR description
- [x] **Submitter**: Make sure Swagger is updated if API changes
- [x] **Submitter**: If updating admin endpoints, also update [firecloud-admin-cli](https://github.com/broadinstitute/firecloud-admin-cli)
- [x] **Submitter**: Check documentation and code comments. Add explanatory PR comments if helpful.
- [x] **Submitter**: JIRA ticket checks:
  - Acceptance criteria exists and is met
  - Note any changes to implementation from the description
  - Add notes on what you've tested
- [x] **Submitter**: Update RC_XXX release ticket with any config or environment changes necessary
- [x] **Submitter**: Update FISMA documentation if changes to:
  - Authentication
  - Authorization
  - Encryption
  - Audit trails
- [x] **Submitter**: If you're adding new libraries, sign us up to security updates for them
- [x] Tell the tech lead (TL) that the PR exists if they wants to look at it
- [x] Anoint a lead reviewer (LR). **Assign PR to LR**
- Review cycle:
  - LR reviews
  - Rest of team may comment on PR at will
  - **LR assigns to submitter** for feedback fixes
  - Submitter rebases to develop again if necessary
  - Submitter makes further commits. DO NOT SQUASH
  - Submitter updates documentation as needed
  - Submitter **reassigns to LR** for further feedback
- [x] **TL** sign off
- [x] **LR** sign off
- [x] **Assign to submitter** to finalize
- [x] **Submitter**: Verify all tests go green, including CI tests
- [x] **Submitter**: Squash commits and merge to develop
- [x] **Submitter**: Delete branch after merge
- [x] **Submitter**: **Test this change works on dev environment after deployment**. YOU own getting it fixed if dev isn't working for ANY reason!
- [x] **Submitter**: Verify swagger UI on dev environment still works after deployment
- [x] **Submitter**: Inform other teams of any API changes via hipchat and/or email
- [x] **Submitter**: Mark JIRA issue as resolved once this checklist is completed

### CODE REVIEW

**Comment by helgridly** [comment]
I think we should be consistent in our representation of attributes, so I'm 😢 on using the plain array representation in some cases and not others. My initial reaction is "update the json schema" but I don't have the context to know if that's possible/easy.

**Comment by davidangb** [comment]
1) This fixes a runtime error in an existing endpoint, so I'm pushing to merge this PR as-is (with any functional/syntax changes, of course), then have a followup conversation about API signature if needed.

2) I don't think we should be consistent here. I've been trying to keep Library datasets and FireCloud workspaces isolated, and treat the APIs differently. If we had made Library a standalone service, this would be less of a concern, but today ... I'd prefer to treat it as a coincidence that Library dataset metadata is backed by workspace attributes, and therefore not tie the two APIs together. Library dataset metadata uses standard json for updates; workspace attributes use an array of operations, or our own customized json.

( this may be better discussed in person )

**Comment by skwalker** [comment]
Fixes the 400 errors we're getting trying to catalog a dataset so I'm ok with it 👍

**Comment by helgridly** [comment]
> I've been trying to keep Library datasets and FireCloud workspaces isolated, and treat the APIs differently

I think this is probably the philosophical difference underpinning our disagreement. Since it's a user-facing issue I'm going to bow out because such decisions are for POs.

**Comment by rushtong** [comment]
👍 Code is saving and returning the right content. UI still needs to fix the display, but this part is working well.

**Comment by rushtong** [comment]
Got the 👍 from hipchat to merge.

**Pull request merged**
