### PR TITLE
get latest versions of scalatest and selenium in Dependencies.scala

### PR DESCRIPTION
**Pull request by aweng98**
\<your comments for this PR go here\>

Have you read [CONTRIBUTING.md](../CONTRIBUTING.md) lately? If not, do that first.

I, the developer opening this PR, do solemnly pinky swear that:

- [ ] I've followed [the instructions](https://github.com/broadinstitute/firecloud-orchestration/blob/develop/CONTRIBUTING.md#api-changes) if I've made any changes to the API, _especially_ if they're breaking changes
- [ ] I've updated the RC_XXX release ticket with any manual steps required to release this change
- [ ] I've updated the [FISMA documentation](https://github.com/broadinstitute/firecloud-orchestration/blob/develop/CONTRIBUTING.md#fisma-documentation-changes) if I've made any security-related changes, including auth, encryption, or auditing

In all cases:

- [ ] Get two thumbsworth of review and PO signoff if necessary
- [ ] Verify all tests go green
- [ ] Squash and merge; you can delete your branch after this **unless it's for a hotfix**. In that case, don't delete it!
- [ ] Test this change deployed correctly and works on dev environment after deployment

### CODE REVIEW

**Comment by aweng98** [comment]
Selenium docker image will be upgraded to latest version 3.11.0. Version in this repo doesn't match that breaks the job.
https://fc-jenkins.dsp-techops.broadinstitute.org/job/firecloud-orchestration-fiab-test-runner/67/

**Review by davidangb — APPROVED** [review]
👍 lgtm, assuming tests all pass. Thanks!

**Comment by aweng98** [comment]
`continuous-integration/travis-ci/pr` check failed.

jenkins retest

**Comment by aweng98** [comment]
jenkins job pass:  https://fc-jenkins.dsp-techops.broadinstitute.org/job/firecloud-orchestration-PR-fiab-test/147/

**Pull request merged**
