### PR TITLE
GAWB-102: use http gzip compression for entity lists

### PR DESCRIPTION
**Pull request by davidangb**
For entity lists - the `workspaces / Segment / Segment / entities_with_type` endpoint that powers the Data tab inside a workspace - enable http gzip encoding.

We don't want to enable gzip for all endpoints, because it adds processing overhead for little-to-no benefit on small responses. However, this endpoint tends to get pretty big, so gzip is worth it.

I have seen 18MB responses from this endpoint compress to under .5 MB.

A good follow-on PR would enable gzip encoding between rawls and orchestration. This only enables it between orchestration and the browser.
# 
- [x] **Submitter**: Rebase to develop. DO NOT SQUASH
- [x] **Submitter**: Make sure Swagger is updated if API changes
- [x] **Submitter**: Make sure documentation for code is complete
- [x] **Submitter**: Review code comments; remove done TODOs, create stories for remaining TODOs
- [x] **Submitter**: Include the JIRA issue number in the PR description
- [x] **Submitter**: Add description or comments on the PR explaining the hows/whys (if not obvious)
- [x] **Submitter**: Tell tech lead that the PR exists if s/he wants to look at it
- [x] **Submitter**: Anoint a lead reviewer (LR). **Assign PR to LR**
- [x] **LR**: Initial review by LR and others.
- [x] Comment / review / update cycle:
  - Rest of team may comments on PR at will
  - **LR assigns to submitter** for feedback fixes
  - Submitter updates documentation as needed
  - Submitter rebases to develop again if necessary
  - Submitter makes further commits. DO NOT SQUASH. **Reassign to LR** for further feedback
- [x] **Tech lead**:  sign off
- [x] **LR**: sign off
- [x] **Assign to submitter** to finalize
- [x] **Submitter**: Squash commits, rebase if necessary
- [x] **Submitter**: Verify all tests go green, including CI tests
- [x] **Submitter**: Merge to develop 
- [x] **Submitter**: Delete branch after merge
- [x] **Submitter**: Check configuration files in Jenkins in case they need changes
- [x] **Submitter**: **Test this change works on dev environment after deployment**. YOU own getting it fixed if dev isn't working for ANY reason!
- [x] **Submitter**: Verify swagger UI on dev server still works after deployment
- [x] **Submitter**: Inform other teams of any API changes via hipchat and/or email
- [x] **Submitter**: Mark JIRA issue as resolved once this checklist is completed

### CODE REVIEW

**Comment by helgridly** [comment]
_hyperventilates with happiness_

**Comment by davidangb** [comment]
this does not complete GAWB-102; it is just a super quick fix along the path of that story.

**Comment by dmohs** [comment]
:+1: I am happy with this, but if it works I suggest we wrap nearly every response with this thing.

**Comment by davidangb** [comment]
I disagree - we should not wrap nearly every response with this. For small payloads, the reduction in size is negligible (and for very small payloads, the gzip dictionary actually ADDS size), and we add compression/decompression overhead on both the server and the browser. But we can add it to more places.

**Comment by dmohs** [comment]
@davidangb I retract my suggestion. I agree with you.

**Pull request merged**
