### PR TITLE
GAWB-1097: explicitly pull in latest versions of jackson libs

### PR DESCRIPTION
**Pull request by davidangb**
See Jira ticket for context.

Instead of relying on transitive dependencies, explicitly pull in jackson libs and tie them to a known version.

Because this changes the libs used by other third-party libraries, it has a nonzero risk of regression; but I assume that risk is small. Unit tests pass and a modest clickthrough of the app still works.

FWIW, when I run `sbt assembly` locally, it pulls in:

```
[info] Including: google-http-client-jackson2-1.22.0.jar
[info] Including: jackson-annotations-2.8.4.jar
[info] Including: jackson-core-2.8.4.jar
[info] Including: jackson-databind-2.8.4.jar
[info] Including: jackson-dataformat-cbor-2.8.1.jar
[info] Including: jackson-dataformat-smile-2.8.1.jar
[info] Including: jackson-dataformat-yaml-2.8.1.jar
[info] Including: json4s-jackson_2.11-3.2.10.jar
```

- [x] **Submitter**: Include the JIRA issue number in the PR description
- [x] **Submitter**: Make sure Swagger is updated if API changes
- [x] **Submitter**: If updating admin endpoints, also update [firecloud-admin-cli](https://github.com/broadinstitute/firecloud-admin-cli)
- [x] **Submitter**: Check documentation and code comments. Add explanatory PR comments if helpful.
- [x] **Submitter**: JIRA ticket checks:
  * Acceptance criteria exists and is met
  * Note any changes to implementation from the description
  * Add notes on what you've tested
- [x] **Submitter**: Update RC_XXX release ticket with any config or environment changes necessary
- [x] **Submitter**: Update FISMA documentation if changes to:
  * Authentication
  * Authorization
  * Encryption
  * Audit trails
- [x] **Submitter**: If you're adding new libraries, sign us up to security updates for them
- [x] Tell the tech lead (TL) that the PR exists if they wants to look at it
- [x] Anoint a lead reviewer (LR). **Assign PR to LR**
* Review cycle:
  * LR reviews
  * Rest of team may comment on PR at will
  * **LR assigns to submitter** for feedback fixes
  * Submitter rebases to develop again if necessary
  * Submitter makes further commits. DO NOT SQUASH
  * Submitter updates documentation as needed
  * Submitter **reassigns to LR** for further feedback
- [x] **TL** sign off
- [x] **LR** sign off
- [x] **Assign to submitter** to finalize
- [x] **Submitter**: Verify all tests go green, including CI tests
- [x] **Submitter**: Squash commits and merge to develop
- [x] **Submitter**: Delete branch after merge
- [ ] **Submitter**: **Test this change works on dev environment after deployment**. YOU own getting it fixed if dev isn't working for ANY reason!
- [ ] **Submitter**: Verify swagger UI on dev environment still works after deployment
- [ ] **Submitter**: Inform other teams of any API changes via hipchat and/or email
- [ ] **Submitter**: Mark JIRA issue as resolved once this checklist is completed

### CODE REVIEW

**Comment by helgridly** [comment]
seems legit to me. i'm assuming that whichever things previously pulled in jackson themselves are now referencing the 2.8.4 version, rather than pulling down their original ones too and referencing those.

**Comment by davidangb** [comment]
Yes - the snippet I included from sbt assembly (`[info] Including: jackson-core-2.8.4.jar ...`) shows the versions that are included in the final jar. So, these are the versions that will be used by anything in the app.

**Comment by jmthibault79** [comment]
I would add a comment above these explaining why we want to be explicit here, in case a future dev thinks "well, `foo` already takes in Jackson" and removes it

**Comment by helgridly** [comment]
+1 Joel's comment.

**Comment by helgridly** [comment]
👍

**Pull request merged**
