### PR TITLE
Make sure containers restart if Docker restarts or if they fall over

### PR DESCRIPTION
**Pull request by coreone**

### CODE REVIEW

**Comment by davidangb** [comment]
@coreone these changes need to make it into the new configuration model - see #197 . I assume the "restart: always" also needs to go into other containers, like firecloud-ui and rawls?

**Comment by coreone** [comment]
@davidangb I can definitely make the same basic change when we change out the base container for this repo.  Additionally, PRs have been put in for this same thing on all other repos in Firecloud:

https://broadinstitute.atlassian.net/browse/DO-740

**Comment by dmohs** [comment]
@coreone I created a PR for firecloud-develop (where configs go now) to get these in: https://github.com/broadinstitute/firecloud-develop/pull/2

**Comment by rushtong** [comment]
This PR affects the README. The section on sbt restart will no longer be valid, if I am understanding this PR correctly.

**Comment by davidangb** [comment]
since this is replaced by broadinstitute/firecloud-develop#2, @coreone could you please close this one?

**Comment by coreone** [comment]
@davidangb Just made the following PR.  If it is accepted and we start deploying using the new method, this PR can just be closed and the branch deleted.

https://github.com/broadinstitute/firecloud-develop/pull/5

**Comment by davidangb** [comment]
closing, per verbal discussion with Andrew, in favor of broadinstitute/firecloud-develop#5

**Pull request closed without merging**
