### PR TITLE
fix assembly AGAIN - use merge strategy instead of shading

### PR DESCRIPTION
**Pull request by davidangb**
Let's try this again - I'm embarrassed. Dev env is currently broken; this should fix it.

This change:
- uses the joda-time and joda-convert that elasticsearch pulls in as a dependency, instead of the versions we explicitly requested (elasticsearch's are more recent anyway)
- resolve duplicate-class conflicts with a straightforward merge strategy, instead of trying to use tricky shading.

(no jira ticket)
- [x] **Submitter**: Include the JIRA issue number in the PR description
- [x] **Submitter**: Make sure Swagger is updated if API changes
- [x] **Submitter**: If updating admin endpoints, also update [firecloud-admin-cli](https://github.com/broadinstitute/firecloud-admin-cli)
- [x] **Submitter**: Check documentation and code comments. Add explanatory PR comments if helpful.
- [x] **Submitter**: JIRA ticket checks:
  - Acceptance criteria exists and is met
  - Note any changes to implementation from the description
  - Add notes on what you've tested
- [x] **Submitter**: Update RC_XXX release ticket with any config or environment changes necessary
- [x] **Submitter**: Update FISMA documentation if changes to:
  - Authentication
  - Authorization
  - Encryption
  - Audit trails
- [x] **Submitter**: If you're adding new libraries, sign us up to security updates for them
- [x] Tell the tech lead (TL) that the PR exists if they wants to look at it
- [x] Anoint a lead reviewer (LR). **Assign PR to LR**
- Review cycle:
  - LR reviews
  - Rest of team may comment on PR at will
  - **LR assigns to submitter** for feedback fixes
  - Submitter rebases to develop again if necessary
  - Submitter makes further commits. DO NOT SQUASH
  - Submitter updates documentation as needed
  - Submitter **reassigns to LR** for further feedback
- [x] **TL** sign off
- [ ] **LR** sign off
- [ ] **Assign to submitter** to finalize
- [ ] **Submitter**: Verify all tests go green, including CI tests
- [ ] **Submitter**: Squash commits and merge to develop
- [ ] **Submitter**: Delete branch after merge
- [ ] **Submitter**: **Test this change works on dev environment after deployment**. YOU own getting it fixed if dev isn't working for ANY reason!
- [ ] **Submitter**: Verify swagger UI on dev environment still works after deployment
- [ ] **Submitter**: Inform other teams of any API changes via hipchat and/or email
- [ ] **Submitter**: Mark JIRA issue as resolved once this checklist is completed

### CODE REVIEW

**Comment by jmthibault79** [comment]
Builds and runs for me with `java -jar <orch>.jar` on the local environment, and responds to Swagger and UI requests.

**Comment by rushtong** [comment]
Docker pull is super sloooooow - still testing

**Comment by jmthibault79** [comment]
This approach looks cleaner, to my limited understanding.  👍

**Comment by rushtong** [comment]
I'm not able to get this running under our current local docker process:

```
proxy_1  | [Fri Oct 14 10:47:08.336178 2016] [proxy:error] [pid 36:tid 139927148820224] (111)Connection refused: AH00957: HTTP: attempt to connect to 172.17.0.4:8080 (app) failed
proxy_1  | [Fri Oct 14 10:47:08.336274 2016] [proxy:error] [pid 36:tid 139927148820224] AH00959: ap_proxy_connect_backend disabling worker for (app) for 60s
proxy_1  | [Fri Oct 14 10:47:08.337472 2016] [proxy_http:error] [pid 36:tid 139927148820224] [client 172.17.0.1:38338] AH01114: HTTP: failed to make connection to backend: app
```

If you're comfortable with this, @davidangb, please go ahead and merge - I'll see if I can sort out what's happening with the local config.

**Comment by rushtong** [comment]
👍 OK, just got this working - had to be my environment.

**Pull request merged**
