### PR TITLE
Apply column/attribute mapping in the reverse order for TSV output

### PR DESCRIPTION
**Pull request by jmthibault79**
Attempt at GAWB-2 but not yet tested on a running Orchestration instance

### CODE REVIEW

**Comment by rushtong** [comment]
We're touching a lot of the same code for GAWB-1. Perhaps we can collaborate?

**Comment by jmthibault79** [comment]
Sure.  Do you have a branch I can look at?

**Comment by rushtong** [comment]
Yes - here: https://github.com/broadinstitute/firecloud-orchestration/tree/gr-GAWB-1

**Comment by jmthibault79** [comment]
Verified on a local Orchestration

**Comment by jmthibault79** [comment]
Please hold off on review.  This conflicts with GAWB-1 so let's do one of these at a time.

**Comment by rushtong** [comment]
:+1: Code looks good, tests pass. I'm happy with this - feel free to rebase and squash.

**Pull request merged**
