### PR TITLE
Swagger: use SubmissionRequest instead of SubmissionIngest

### PR DESCRIPTION
**Pull request by rtitle**
See: https://broadinstitute.atlassian.net/browse/GAWB-2220

Previously I had just updated `SubmissionRequest`, not `SubmissionIngest`.

- [x] **Submitter**: Include the JIRA issue number in the PR description
- [x] **Submitter**: Make sure Swagger is updated if API changes
- [x] **Submitter**: If updating admin endpoints, also update [firecloud-admin-cli](https://github.com/broadinstitute/firecloud-admin-cli)
- [x] **Submitter**: Check documentation and code comments. Add explanatory PR comments if helpful.
- [x] **Submitter**: JIRA ticket checks:
  * Acceptance criteria exists and is met
  * Note any changes to implementation from the description
  * To Demo flag is set
  * Release Summary is filled out, if applicable
  * Add notes on how to QA
- [x] **Submitter**: Update RC_XXX release ticket with any config or environment changes necessary
- [x] **Submitter**: Update FISMA documentation if changes to:
  * Authentication
  * Authorization
  * Encryption
  * Audit trails
- [x] Tell the tech lead (TL) that the PR exists if they wants to look at it
- [x] Anoint a lead reviewer (LR). **Assign PR to LR**
* Review cycle:
  * LR reviews
  * Rest of team may comment on PR at will
  * **LR assigns to submitter** for feedback fixes
  * Submitter rebases to develop again if necessary
  * Submitter makes further commits. DO NOT SQUASH
  * Submitter updates documentation as needed
  * Submitter **reassigns to LR** for further feedback
- [x] **TL** sign off
- [x] **LR** sign off
- [x] **Product Owner** sign off
- [x] **Assign to submitter** to finalize
- [x] **Submitter**: Verify all tests go green, including CI tests
- [x] **Submitter**: Squash commits and merge to develop
- [x] **Submitter**: Delete branch after merge
- [x] **Submitter**: **Test this change works on dev environment after deployment**. YOU own getting it fixed if dev isn't working for ANY reason!
- [x] **Submitter**: Verify swagger UI on dev environment still works after deployment
- [x] **Submitter**: Inform other teams of any API changes via Slack and/or email
- [x] **Submitter**: Mark JIRA issue as resolved once this checklist is completed

### CODE REVIEW

**Comment by davidangb** [comment]
( don't hold the PR for this, but ...)

You can specify both the default and the value restrictions in swagger, like this:
```
      workflowFailureMode:
        type: string
        description: What happens after a task fails. Choose from ContinueWhilePossible and NoNewCalls. Defaults to NoNewCalls if not specified. See Cromwell docs for more information.
        default: NoNewCalls
        enum: ["NoNewCalls","ContinueWhilePossible"]
```

( swagger-ui doesn't render enums very well, boo. )

**Comment by rtitle** [comment]
Cool. I tried it locally and it works, so I made the change :)

**Review by davidangb — APPROVED** [review]
lgtm!

**Comment by jmthibault79** [comment]
The actual case class used in Workspace.scala is `SubmissionIngest` so change its name to `SubmissionRequest` also

**Review by jmthibault79 — APPROVED** [review]

**Pull request merged**
