### PR TITLE
individual tests should not write to/read from the same files

### PR DESCRIPTION
**Pull request by davidangb**
Multiple tests in the same spec were using the same file as a fixture - creating it, setting ACLs on it, and deleting it. However, the delete step is a `Future` and we don't wait for deletion to complete before starting the next test. Therefore it's possible for multiple tests to interfere with each other.

We also want the tests to be totally isolated so we could enable parallel tests at some point in the future.

This PR changes the tests so that each test uses an isolated copy of the file.

There were a bunch of test runs before I properly re-enabled tests and those runs should be ignored. Summarizing the test results after re-enabling from the mess of comments below:
* five successful manual runs of swatomation-pipeline (these skipped UI, sam, leo, rawls tests)
* three "successful" runs of swatomation-pipeline via PR trigger:
** all three passed orch integration tests, which is what this PR is about
** one passed 100%
** two failed on unrelated Selenium tests, which I claim are unrelated to this PR

Have you read [CONTRIBUTING.md](../CONTRIBUTING.md) lately? If not, do that first.

I, the developer opening this PR, do solemnly pinky swear that:

- [x] I've followed [the instructions](https://github.com/broadinstitute/firecloud-orchestration/blob/develop/CONTRIBUTING.md#api-changes) if I've made any changes to the API, _especially_ if they're breaking changes
- [x] I've updated the RC_XXX release ticket with any manual steps required to release this change
- [x] I've updated the [FISMA documentation](https://github.com/broadinstitute/firecloud-orchestration/blob/develop/CONTRIBUTING.md#fisma-documentation-changes) if I've made any security-related changes, including auth, encryption, or auditing

In all cases:

- [ ] Get two thumbsworth of review and PO signoff if necessary
- [ ] Verify all tests go green
- [ ] Squash and merge; you can delete your branch after this **unless it's for a hotfix**. In that case, don't delete it!
- [ ] Test this change deployed correctly and works on dev environment after deployment

### CODE REVIEW

**Comment by davidangb** [comment]
first test run passed everything. Let's do it again: jenkins retest.

**Comment by davidangb** [comment]
an orch unit test failed:
```
[info] - should return OK when an expired user re-links. their new link time should be 30 days in the future *** FAILED ***
[info]   1528753976 was not greater than or equal to 1528753977 (NihApiServiceSpec.scala:126)
```
which seems unrelated. Jenkins retest.

**Comment by davidangb** [comment]
third test run passed everything.

**Comment by davidangb** [comment]
one more time to prove repetition: jenkins retest.

**Comment by davidangb** [comment]
arg I hadn't re-enabled the tests in the previous runs! Let's start over. Passed all automation one time, going for another run: jenkins retest.

**Comment by davidangb** [comment]
manual swatomation-pipeline run 1 passed.

**Comment by davidangb** [comment]
manual swatomation-pipeline run 2 passed.

**Comment by davidangb** [comment]
manual swatomation-pipeline run 3 passed.

**Comment by davidangb** [comment]
full PR swatomation run failed overall, though the integration tests in question passed:
```
[info] *** 3 TESTS FAILED ***
[error] Failed: Total 124, Failed 3, Errors 0, Passed 121, Ignored 3
[error] Failed tests:
[error] 	org.broadinstitute.dsde.firecloud.test.workspace.WorkspaceOwnerSpec
[error] 	org.broadinstitute.dsde.firecloud.test.user.SignInSpec
[error] 	org.broadinstitute.dsde.firecloud.test.library.DataUseAwareSearchSpec
```
one more time for repeatability: jenkins retest

**Comment by davidangb** [comment]
manual swatomation-pipeline run 4 passed.

**Comment by davidangb** [comment]
manual swatomation-pipeline run 5 passed.

**Comment by davidangb** [comment]
third full swatomation run failed overall, though the integration tests in question passed:
```
[info] *** 1 TEST FAILED ***
[error] Failed: Total 124, Failed 1, Errors 0, Passed 123, Ignored 3
[error] Failed tests:
[error] 	org.broadinstitute.dsde.firecloud.test.library.DataLibrarySpec
```

**Review by jmthibault79 — APPROVED** [review]
This approach makes sense

**Review by gdlex4015 — APPROVED** [review]

**Pull request merged**
