### PR TITLE
more DUL-search use case integration tests

### PR DESCRIPTION
**Pull request by davidangb**
Update use-case integration tests according to the spreadsheet provided by Moran.

The results of these integration tests are exactly the same as what Greg found in manual testing. Given that, I've also ignored the three tests that are failing.

Have you read [CONTRIBUTING.md](../CONTRIBUTING.md) lately? If not, do that first.

I, the developer opening this PR, do solemnly pinky swear that:

- [x] I've followed [the instructions](https://github.com/broadinstitute/firecloud-orchestration/blob/develop/CONTRIBUTING.md#api-changes) if I've made any changes to the API, _especially_ if they're breaking changes
- [x] I've updated the RC_XXX release ticket with any manual steps required to release this change
- [x] I've updated the [FISMA documentation](https://github.com/broadinstitute/firecloud-orchestration/blob/develop/CONTRIBUTING.md#fisma-documentation-changes) if I've made any security-related changes, including auth, encryption, or auditing

In all cases:

- [ ] Get two thumbsworth of review and PO signoff if necessary
- [ ] Verify all tests go green
- [ ] Squash and merge; you can delete your branch after this **unless it's for a hotfix**. In that case, don't delete it!
- [ ] Test this change deployed correctly and works on dev environment after deployment

### CODE REVIEW

**Review by ahaessly — APPROVED** [review]
👍

**Comment by davidangb** [comment]
jenkins retest

**Comment by davidangb** [comment]
jenkins retest

**Review by rushtong — APPROVED** [review]
👍 Matched up the cases one by one ... all look correct.

**Comment by ahaessly** [comment]
👍

**Pull request merged**
