### PR TITLE
AJ-1141 debugging README

### PR DESCRIPTION
**Pull request by calypsomatic**
It was not easy to figure out how to debug firecloud-orchestration, which in the end requires a completely unexpected change to `build.sbt`.  To save others from this struggle, I have added the steps I went through to the README.

### CODE REVIEW

**Comment by calypsomatic** [comment]
jenkins retest

**Comment by calypsomatic** [comment]
jenkins retest

**Review by davidangb — APPROVED** [review]
nice find! This is curious - do you know what made the difference?

Looking at `Revolver.enableDebugging` I see https://github.com/spray/sbt-revolver/blob/4d28f091d3f2ce2f7f28b0165bac6705effded9a/src/main/scala/spray/revolver/DebugSettings.scala#L5 … the only difference I note is `address=*:5051` vs `address=5051`, was that it?

Either way, if it works, it works, I'm good with it.

**Comment by calypsomatic** [comment]
> nice find! This is curious - do you know what made the difference?
> 
No, it was just black magic of trying different things until something worked!

**Pull request merged**
