### PR TITLE
Columns required for display in search results

### PR DESCRIPTION
**Pull request by rushtong**
Fix for https://broadinstitute.atlassian.net/browse/GAWB-1338
See UI companion PR: https://github.com/broadinstitute/firecloud-ui/pull/624

---
- [x] **Submitter**: Include the JIRA issue number in the PR description
- [x] **Submitter**: Make sure Swagger is updated if API changes
- [x] **Submitter**: If updating admin endpoints, also update [firecloud-admin-cli](https://github.com/broadinstitute/firecloud-admin-cli)
- [x] **Submitter**: Check documentation and code comments. Add explanatory PR comments if helpful.
- [x] **Submitter**: JIRA ticket checks:
  * Acceptance criteria exists and is met
  * Note any changes to implementation from the description
  * Add notes on what you've tested
- [x] **Submitter**: Update RC_XXX release ticket with any config or environment changes necessary
- [x] **Submitter**: Update FISMA documentation if changes to:
  * Authentication
  * Authorization
  * Encryption
  * Audit trails
- [x] **Submitter**: If you're adding new libraries, sign us up to security updates for them
- [x] Tell the tech lead (TL) that the PR exists if they wants to look at it
- [x] Anoint a lead reviewer (LR). **Assign PR to LR**
* Review cycle:
  * LR reviews
  * Rest of team may comment on PR at will
  * **LR assigns to submitter** for feedback fixes
  * Submitter rebases to develop again if necessary
  * Submitter makes further commits. DO NOT SQUASH
  * Submitter updates documentation as needed
  * Submitter **reassigns to LR** for further feedback
- [x] **TL** sign off
- [x] **LR** sign off
- [x] **Product Owner** sign off
- [x] **Assign to submitter** to finalize
- [x] **Submitter**: Verify all tests go green, including CI tests
- [x] **Submitter**: Squash commits and merge to develop
- [x] **Submitter**: Delete branch after merge
- [x] **Submitter**: **Test this change works on dev environment after deployment**. YOU own getting it fixed if dev isn't working for ANY reason!
- [x] **Submitter**: Verify swagger UI on dev environment still works after deployment
- [x] **Submitter**: Inform other teams of any API changes via hipchat and/or email
- [x] **Submitter**: Mark JIRA issue as resolved once this checklist is completed

### CODE REVIEW

**Comment by davidangb** [comment]
This is ok as-is, but it feels like we keep duplicating data in this file. Is there any way this could be included as an attribute in one of the other sections, like `properties` or `display`?

**Comment by rushtong** [comment]
I agree that we're duplicating things. I'm not sure how to get around that. The display we currently have is for the summary page and that has different requirements than the display in search results. Different order, different columns, etc. 

I get the feeling we're really overloading this file and maybe we should be looking at a different strategy for maintaining all of this UI-ish logic. Maybe a lot of this can instead be a json file in UI?

**Comment by rushtong** [comment]
@davidangb 
What do you think about this kind of a structure?
```
  "properties": {
    "library:datasetName": {
      "title": "Cohort Name",
      "type": "string",
      "searchResult": {
        "ordinal": 1
      },
    }, ...
```
The pro for this is that we're already do this with `aggregate`. 
The con is that it diverges pretty strongly from other structures like `consentCodes`, `display`, and `wizard`, etc.

**Comment by davidangb** [comment]
yeah, I agree with you that we need a larger overhaul. Go ahead with this as-is, and let's schedule a more comprehensive refactor.

**Comment by davidangb** [comment]
👍 (after rebase/merge)

**Comment by rushtong** [comment]
Gotcha. need to rebase and retest both UI and orch.

**Comment by ahaessly** [comment]
totally agree with comments about the file. i was thinking once matt is back we should meet and discuss

**Review by davidangb — APPROVED** [review]

**Pull request merged**
