### PR TITLE
GAWB-2949: Synchronize status

### PR DESCRIPTION
**Pull request by rushtong**
## Addresses 
One part of https://broadinstitute.atlassian.net/browse/GAWB-2949

## Testing
Tests for this specific code have never failed. To be re-assured that no concurrency problems exist, run `sbt "repeat 100 test-only *ProjectManagerSpec"` 

---

Have you read [CONTRIBUTING.md](../CONTRIBUTING.md) lately? If not, do that first.

I, the developer opening this PR, do solemnly pinky swear that:

- [ ] I've followed [the instructions](https://github.com/broadinstitute/firecloud-orchestration/blob/develop/CONTRIBUTING.md#api-changes) if I've made any changes to the API, _especially_ if they're breaking changes
- [ ] I've updated the RC_XXX release ticket with any manual steps required to release this change
- [ ] I've updated the [FISMA documentation](https://github.com/broadinstitute/firecloud-orchestration/blob/develop/CONTRIBUTING.md#fisma-documentation-changes) if I've made any security-related changes, including auth, encryption, or auditing

In all cases:

- [ ] Get two thumbsworth of review and PO signoff if necessary
- [ ] Verify all tests go green
- [ ] Squash and merge; you can delete your branch after this **unless it's for a hotfix**. In that case, don't delete it!
- [ ] Test this change deployed correctly and works on dev environment after deployment

### CODE REVIEW

**Comment by rushtong** [comment]
jenkins retest

**Comment by rushtong** [comment]
jenkins retest

**Comment by rushtong** [comment]
jenkins retest

**Comment by rushtong** [comment]
jenkins retest

**Comment by kyuksel** [comment]
Consider modifying 
```scala
var currentStatus = idle
```
as
```scala
@volatile private[this] var currentStatus = idle
```
for potentially further safety.

**Review by kyuksel — APPROVED** [review]
👍 with a suggestion for a potential improvement. FWIW, the code I attached to the related Jira ticket does this so the client doesn't need to.

**Review by davidangb — APPROVED** [review]
:+1:

**Comment by rushtong** [comment]
jenkins retest

**Pull request merged**
