### PR TITLE
if free trial user has no profile, still send status fields to spreadsheet [risk: low]

### PR DESCRIPTION
**Pull request by davidangb**
DataBiosphere/firecloud-app#245

in the process that updates our free-credits tracking spreadsheet:
* we originally failed to update the spreadsheet entirely if any user was missing required `Profile`  fields
* as of #706, we successfully update the spreadsheet for fully-populated user, but any user missing fields resulted in an entire row of "ERROR IN FIRECLOUD"  cells.
* as of this PR - now that we understand the use case better - we correctly send the internal fields such as `trialStatus` even if the user is missing `Profile` fields. This means we can track all users through their trials;  some might just be missing firstname/lastname and other cosmetic fields.

The use case for this is Terra - Terra has turned on free trial via their UI,  but don't require a fully-populated `Profile`.

-----

Have you read [CONTRIBUTING.md](../CONTRIBUTING.md) lately? If not, do that first.

I, the developer opening this PR, do solemnly pinky swear that:

- [ ] I've followed [the instructions](https://github.com/broadinstitute/firecloud-orchestration/blob/develop/CONTRIBUTING.md#api-changes) if I've made any changes to the API, _especially_ if they're breaking changes
- [ ] I've updated the RC_XXX release ticket with any manual steps required to release this change
- [ ] I've updated the [FISMA documentation](https://github.com/broadinstitute/firecloud-orchestration/blob/develop/CONTRIBUTING.md#fisma-documentation-changes) if I've made any security-related changes, including auth, encryption, or auditing

In all cases:

- [ ] Get two thumbsworth of review and PO signoff if necessary
- [ ] Verify all tests go green
- [ ] Squash and merge; you can delete your branch after this **unless it's for a hotfix**. In that case, don't delete it!
- [ ] Test this change deployed correctly and works on dev environment after deployment

### CODE REVIEW

**Review by elizzhao — APPROVED** [review]
couldn't test, but code makes sense to me!

**Review by breilly2 — APPROVED** [review]
👍 Interesting technique for setting defaults. I wouldn't have thought of that. I probably would have created a stub profile object with empty string values for all properties. (However I haven't studied this code enough to know whether or not that's possible.) Anyway, while I did not test it myself, I believe that this works and I checked that all of the fields line up positionally.

**Comment by davidangb** [comment]
@breilly2 I wanted to go that path too, but there are `require`ments on the `Profile` object that look for empty strings: https://github.com/broadinstitute/firecloud-orchestration/blob/develop/src/main/scala/org/broadinstitute/dsde/firecloud/model/Profile.scala#L64 ... I didn't want to refactor that because it's used elsewhere in the code.

**Comment by breilly2** [comment]
And that's exactly the kind of thing that I suspected might exist that led to this implementation. :)

**Pull request merged**
